services:
  app:
    entrypoint:
    - sleep
    - infinity
#    image: minepicco/cci-build:22.04
    image: ubuntu:24.04
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock