services:
  app:
    entrypoint:
    - sleep
    - infinity
    # image: minepicco/dev-image:1.0
    image: ubuntu:24.04
    # image: macnicadevops/intel:0.1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
