services:
  app:
    entrypoint:
    - sleep
    - infinity
      image: minepicco/dev-image:1.0
      platform: linux/x86_64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
