services:
  app:
    entrypoint:
    - sleep
    - infinity
      image: ubuntu:20.04
      mac_address: 01:02:0a:0b:22
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
