services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: minepicco/dev-image:1.0
    platform: linux/x86_64
    mac_address: 00:11:22:33:44:55
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
